version: '3.7'

services:
  debian:
    restart: always
    image: go_tpm_driver
    container_name: go_token
    ports:
      - 8040:8040
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - ${APP_BASE_DIR}/go_tpm:/home/go/go_tpm
